export const API_VERSION = 'v2'
export const CAPABILITIES_VERSION = '1'
export const PLATFORM = 'Web'

export const SSE_EVENTS = {
  CONVERSATION_MESSAGE: 'CONVERSATION_MESSAGE',
  CONVERSATION_ROUTING_RESULT: 'CONVERSATION_ROUTING_RESULT',
  CONVERSATION_PARTICIPANT_CHANGED: 'CONVERSATION_PARTICIPANT_CHANGED',
  CONVERSATION_TYPING_STARTED_INDICATOR: 'CONVERSATION_TYPING_STARTED_INDICATOR',
  CONVERSATION_TYPING_STOPPED_INDICATOR: 'CONVERSATION_TYPING_STOPPED_INDICATOR',
  CONVERSATION_DELIVERY_ACKNOWLEDGEMENT: 'CONVERSATION_DELIVERY_ACKNOWLEDGEMENT',
  CONVERSATION_READ_ACKNOWLEDGEMENT: 'CONVERSATION_READ_ACKNOWLEDGEMENT',
  CONVERSATION_CLOSE_CONVERSATION: 'CONVERSATION_CLOSE_CONVERSATION',
  CONVERSATION_SESSION_STATUS_CHANGED: 'CONVERSATION_SESSION_STATUS_CHANGED',
} as const

export const TYPING_INDICATOR_TIMEOUT_MS = 5000
export const SSE_HEARTBEAT_TIMEOUT_MS = 90000
export const SSE_MAX_RECONNECT_ATTEMPTS = 10
export const SSE_INITIAL_RECONNECT_DELAY_MS = 1000
export const SSE_MAX_RECONNECT_DELAY_MS = 30000
export const SSE_RECONNECT_BACKOFF_MULTIPLIER = 1.5
